# Ruff configuration
line-length = 88
target-version = "py38"

[lint]
select = [
    "E",  # pycodestyle errors
    "F",  # pyflakes
    "B",  # flake8-bugbear
    "S",  # flake8-bandit
    "I",  # isort
]
ignore = []

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto" 