[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "bydefault"
version = "0.1.0"
description = "CLI tools for Splunk 9.2.2 TA development and maintenance"
readme = "README.md"
requires-python = ">=3.8"
license = "Proprietary"
authors = [
    { name = "Your Organization" }
]

[project.scripts]
bydefault = "bydefault.cli:main"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "-ra -q"

[tool.ruff]
target-version = "py38"
line-length = 88 